function setGraphicsDefault()
% SETGRAPHICSDEFAULT Set default behaviours for plots.
%
% See also GROOT.

% Author: Xukun Lin
% Date: 05.24.2025

    set(groot, 'DefaultTextInterpreter', 'latex', ...
               'DefaultAxesTickLabelInterpreter', 'latex', ...
               'DefaultAxesFontSize', 18, ...
               'DefaultAxesBox', 'on', ...
               'DefaultLegendLocation', 'best', ...
               'DefaultLegendFontSizeMode', 'manual', ...
               'DefaultLegendFontSize', 18, ...
               'DefaultLegendInterpreter', 'latex', ...
               'DefaultLineLineWidth', 1.4, ...
               'DefaultLegendBox', 'off', ...
               'DefaultAxesTitleFontSizeMultiplier', 1.2, ...
               'DefaultLineMarkerSize', 10, ...
               'DefaultRectangleEdgeColor', 'white', ...
               'DefaultRectangleLineStyle', '--', ...
               'DefaultRectangleLineWidth', 1.4);
               % 'DefaultFigureColor', 'white', ...
end